# Generated by Django 4.1.7 on 2023-02-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_context',
            field=models.TextField(max_length=55),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_title',
            field=models.CharField(max_length=55),
        ),
    ]
